name: Simple Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
      
      - name: Build Windows executable
        run: |
          pyinstaller --onefile --windowed --name "SurvivalCurveExtractor" --hidden-import="PIL._tkinter_finder" main.py
          
      - name: Create Windows ZIP
        shell: pwsh
        run: |
          cd dist
          Compress-Archive -Path "SurvivalCurveExtractor.exe" -DestinationPath "SurvivalCurveExtractor-Windows-x64.zip"
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/SurvivalCurveExtractor-Windows-x64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
      
      - name: Build macOS executable
        run: |
          pyinstaller survival_curve_extractor.spec
          
      - name: Create macOS ZIP
        run: |
          cd dist
          zip -r "SurvivalCurveExtractor-macOS-$(uname -m).zip" "SurvivalCurveExtractor.app"
      
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/SurvivalCurveExtractor-macOS-*.zip

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-build/*.zip
            artifacts/macos-build/*.zip
          body: |
            ## Survival Curve Extractor Release
            
            ### Installation Instructions
            
            #### Windows
            1. Download `SurvivalCurveExtractor-Windows-x64.zip`
            2. Extract the ZIP file
            3. Run `SurvivalCurveExtractor.exe`
            
            #### macOS
            1. Download the appropriate file for your Mac:
               - `SurvivalCurveExtractor-macOS-arm64.zip` for M1/M2 Macs
               - `SurvivalCurveExtractor-macOS-x64.zip` for Intel Macs
            2. Extract the ZIP file
            3. Right-click the app and select "Open"
            
            See the [User Guide](https://github.com/NikitiusIv/survival_curves_extractor/blob/main/USER_GUIDE.md) for detailed instructions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}