name: Simple Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
      
      - name: Build Windows executable
        run: |
          pyinstaller --onefile --windowed --name "SurvivalCurveExtractor" --hidden-import="PIL._tkinter_finder" main.py
          
      - name: Create Windows ZIP
        shell: pwsh
        run: |
          cd dist
          Compress-Archive -Path "SurvivalCurveExtractor.exe" -DestinationPath "SurvivalCurveExtractor-Windows-x64.zip"
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/SurvivalCurveExtractor-Windows-x64.zip

  build-macos-arm64:
    runs-on: macos-latest  # Apple Silicon (M1/M2)
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
      
      - name: Build macOS ARM64 executable
        run: |
          pyinstaller survival_curve_extractor.spec
          
      - name: Create macOS ARM64 ZIP
        run: |
          cd dist
          zip -r "SurvivalCurveExtractor-macOS-arm64.zip" "SurvivalCurveExtractor.app"
      
      - name: Upload macOS ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: dist/SurvivalCurveExtractor-macOS-arm64.zip

  build-macos-intel:
    runs-on: macos-13  # Intel-based Mac
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
      
      - name: Build macOS Intel executable
        run: |
          pyinstaller survival_curve_extractor.spec
          
      - name: Create macOS Intel ZIP
        run: |
          cd dist
          zip -r "SurvivalCurveExtractor-macOS-x64.zip" "SurvivalCurveExtractor.app"
      
      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-build
          path: dist/SurvivalCurveExtractor-macOS-x64.zip

  create-release:
    needs: [build-windows, build-macos-arm64, build-macos-intel]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: List downloaded artifacts
        run: |
          find artifacts -type f -name "*.zip" -ls
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows-build/*.zip
            artifacts/macos-arm64-build/*.zip
            artifacts/macos-intel-build/*.zip
          body: |
            ## Survival Curve Extractor Release
            
            ### Installation Instructions
            
            #### Windows
            1. Download `SurvivalCurveExtractor-Windows-x64.zip`
            2. Extract the ZIP file
            3. Run `SurvivalCurveExtractor.exe`
            
            #### macOS
            **Apple Silicon (M1/M2/M3):**
            1. Download `SurvivalCurveExtractor-macOS-arm64.zip`
            2. Extract the ZIP file
            3. Right-click the app and select "Open"
            
            **Intel-based Mac (i5/i7):**
            1. Download `SurvivalCurveExtractor-macOS-x64.zip`
            2. Extract the ZIP file
            3. Right-click the app and select "Open"
            
            See the [User Guide](https://github.com/NikitiusIv/survival_curves_extractor/blob/main/USER_GUIDE.md) for detailed instructions.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}